# Generated by Django 3.2.5 on 2021-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrefGodsForMotd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motdName', models.CharField(max_length=512)),
                ('godID', models.IntegerField()),
                ('godName', models.CharField(max_length=128)),
                ('godImageUrl', models.CharField(max_length=512)),
                ('wins', models.IntegerField(null=True)),
                ('loses', models.IntegerField(null=True)),
                ('ratio', models.FloatField(null=True)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
