# Generated by Django 3.2.5 on 2021-08-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.CharField(max_length=256, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
