# Generated by Django 3.2.5 on 2021-08-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motd',
            name='description',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='motd',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
