# Generated by Django 3.2.5 on 2021-08-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0002_auto_20210814_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrefGodsForMotd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('god_id', models.IntegerField()),
                ('god_name', models.CharField(max_length=128)),
                ('god_image_url', models.CharField(max_length=512)),
                ('motd_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='motd',
            name='mod_id',
            field=models.IntegerField(null=True),
        ),
    ]
