# Generated by Django 3.2.5 on 2021-08-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0006_rename_modid_motd_motdid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfMotds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motdID', models.IntegerField(null=True)),
                ('nameOfMotd', models.CharField(max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='MotdsToGods',
        ),
    ]
