# Generated by Django 3.2.5 on 2021-08-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0007_auto_20210820_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListOfMotds',
        ),
    ]
