# Generated by Django 3.2.5 on 2021-08-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0008_delete_listofmotds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefgodsformotd',
            name='motdID',
        ),
    ]
