# Generated by Django 3.2.5 on 2021-08-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0009_remove_prefgodsformotd_motdid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfMotds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motdID', models.IntegerField()),
            ],
            options={
                'db_table': 'ListOfMotds',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='motd',
            name='motdID',
        ),
        migrations.AddField(
            model_name='prefgodsformotd',
            name='motdID',
            field=models.IntegerField(null=True),
        ),
    ]
