# Generated by Django 3.2.5 on 2021-08-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0010_auto_20210820_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListOfMotds',
        ),
        migrations.RemoveField(
            model_name='prefgodsformotd',
            name='motdID',
        ),
        migrations.AddField(
            model_name='prefgodsformotd',
            name='motdName',
            field=models.CharField(default='', max_length=512),
        ),
    ]
