# Generated by Django 3.2.5 on 2021-08-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smite_lore', '0011_auto_20210820_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefgodsformotd',
            name='loses',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prefgodsformotd',
            name='ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='prefgodsformotd',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prefgodsformotd',
            name='wins',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prefgodsformotd',
            name='motdName',
            field=models.CharField(max_length=512),
        ),
    ]
