name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          sudo systemctl daemon-reload
          sudo systemctl restart gunicorn